version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  memcached:
    image: memcached:1.6
    container_name: booking_memcached
    ports:
      - "11211:11211"

volumes:
  postgres_data:
